/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransferRouteImport } from './routes/_app.transfer'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPfmRouteImport } from './routes/_app.pfm'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppOpenFdRouteImport } from './routes/_app.open-fd'
import { Route as AppMobileRechargeRouteImport } from './routes/_app.mobile-recharge'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppInvestmentsRouteImport } from './routes/_app.investments'
import { Route as AppInsuranceRouteImport } from './routes/_app.insurance'
import { Route as AppGovtSchemesRouteImport } from './routes/_app.govt-schemes'
import { Route as AppDepositsRouteImport } from './routes/_app.deposits'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCardsRouteImport } from './routes/_app.cards'
import { Route as AppBeneficiariesRouteImport } from './routes/_app.beneficiaries'
import { Route as AppAsbaIpoRouteImport } from './routes/_app.asba-ipo'
import { Route as AppApplyLoanRouteImport } from './routes/_app.apply-loan'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppPayBillsIndexRouteImport } from './routes/_app.pay-bills.index'
import { Route as AppPayBillsWaterRouteImport } from './routes/_app.pay-bills.water'
import { Route as AppPayBillsMobileRouteImport } from './routes/_app.pay-bills.mobile'
import { Route as AppPayBillsGasRouteImport } from './routes/_app.pay-bills.gas'
import { Route as AppPayBillsElectricityRouteImport } from './routes/_app.pay-bills.electricity'
import { Route as AppPayBillsCreditCardRouteImport } from './routes/_app.pay-bills.credit-card'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPfmRoute = AppPfmRouteImport.update({
  id: '/pfm',
  path: '/pfm',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppOpenFdRoute = AppOpenFdRouteImport.update({
  id: '/open-fd',
  path: '/open-fd',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileRechargeRoute = AppMobileRechargeRouteImport.update({
  id: '/mobile-recharge',
  path: '/mobile-recharge',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppInsuranceRoute = AppInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AppRoute,
} as any)
const AppGovtSchemesRoute = AppGovtSchemesRouteImport.update({
  id: '/govt-schemes',
  path: '/govt-schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositsRoute = AppDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AppRoute,
} as any)
const AppAsbaIpoRoute = AppAsbaIpoRouteImport.update({
  id: '/asba-ipo',
  path: '/asba-ipo',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyLoanRoute = AppApplyLoanRouteImport.update({
  id: '/apply-loan',
  path: '/apply-loan',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsIndexRoute = AppPayBillsIndexRouteImport.update({
  id: '/pay-bills/',
  path: '/pay-bills/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsWaterRoute = AppPayBillsWaterRouteImport.update({
  id: '/pay-bills/water',
  path: '/pay-bills/water',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsMobileRoute = AppPayBillsMobileRouteImport.update({
  id: '/pay-bills/mobile',
  path: '/pay-bills/mobile',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsGasRoute = AppPayBillsGasRouteImport.update({
  id: '/pay-bills/gas',
  path: '/pay-bills/gas',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsElectricityRoute = AppPayBillsElectricityRouteImport.update({
  id: '/pay-bills/electricity',
  path: '/pay-bills/electricity',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsCreditCardRoute = AppPayBillsCreditCardRouteImport.update({
  id: '/pay-bills/credit-card',
  path: '/pay-bills/credit-card',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AppAccountsRoute
  '/apply-loan': typeof AppApplyLoanRoute
  '/asba-ipo': typeof AppAsbaIpoRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposits': typeof AppDepositsRoute
  '/govt-schemes': typeof AppGovtSchemesRoute
  '/insurance': typeof AppInsuranceRoute
  '/investments': typeof AppInvestmentsRoute
  '/loans': typeof AppLoansRoute
  '/mobile-recharge': typeof AppMobileRechargeRoute
  '/open-fd': typeof AppOpenFdRoute
  '/payments': typeof AppPaymentsRoute
  '/pfm': typeof AppPfmRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/transactions': typeof AppTransactionsRoute
  '/transfer': typeof AppTransferRoute
  '/pay-bills/credit-card': typeof AppPayBillsCreditCardRoute
  '/pay-bills/electricity': typeof AppPayBillsElectricityRoute
  '/pay-bills/gas': typeof AppPayBillsGasRoute
  '/pay-bills/mobile': typeof AppPayBillsMobileRoute
  '/pay-bills/water': typeof AppPayBillsWaterRoute
  '/pay-bills/': typeof AppPayBillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AppAccountsRoute
  '/apply-loan': typeof AppApplyLoanRoute
  '/asba-ipo': typeof AppAsbaIpoRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposits': typeof AppDepositsRoute
  '/govt-schemes': typeof AppGovtSchemesRoute
  '/insurance': typeof AppInsuranceRoute
  '/investments': typeof AppInvestmentsRoute
  '/loans': typeof AppLoansRoute
  '/mobile-recharge': typeof AppMobileRechargeRoute
  '/open-fd': typeof AppOpenFdRoute
  '/payments': typeof AppPaymentsRoute
  '/pfm': typeof AppPfmRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/transactions': typeof AppTransactionsRoute
  '/transfer': typeof AppTransferRoute
  '/pay-bills/credit-card': typeof AppPayBillsCreditCardRoute
  '/pay-bills/electricity': typeof AppPayBillsElectricityRoute
  '/pay-bills/gas': typeof AppPayBillsGasRoute
  '/pay-bills/mobile': typeof AppPayBillsMobileRoute
  '/pay-bills/water': typeof AppPayBillsWaterRoute
  '/pay-bills': typeof AppPayBillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/apply-loan': typeof AppApplyLoanRoute
  '/_app/asba-ipo': typeof AppAsbaIpoRoute
  '/_app/beneficiaries': typeof AppBeneficiariesRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deposits': typeof AppDepositsRoute
  '/_app/govt-schemes': typeof AppGovtSchemesRoute
  '/_app/insurance': typeof AppInsuranceRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/mobile-recharge': typeof AppMobileRechargeRoute
  '/_app/open-fd': typeof AppOpenFdRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/pfm': typeof AppPfmRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/transfer': typeof AppTransferRoute
  '/_app/pay-bills/credit-card': typeof AppPayBillsCreditCardRoute
  '/_app/pay-bills/electricity': typeof AppPayBillsElectricityRoute
  '/_app/pay-bills/gas': typeof AppPayBillsGasRoute
  '/_app/pay-bills/mobile': typeof AppPayBillsMobileRoute
  '/_app/pay-bills/water': typeof AppPayBillsWaterRoute
  '/_app/pay-bills/': typeof AppPayBillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/apply-loan'
    | '/asba-ipo'
    | '/beneficiaries'
    | '/cards'
    | '/dashboard'
    | '/deposits'
    | '/govt-schemes'
    | '/insurance'
    | '/investments'
    | '/loans'
    | '/mobile-recharge'
    | '/open-fd'
    | '/payments'
    | '/pfm'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/transfer'
    | '/pay-bills/credit-card'
    | '/pay-bills/electricity'
    | '/pay-bills/gas'
    | '/pay-bills/mobile'
    | '/pay-bills/water'
    | '/pay-bills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/apply-loan'
    | '/asba-ipo'
    | '/beneficiaries'
    | '/cards'
    | '/dashboard'
    | '/deposits'
    | '/govt-schemes'
    | '/insurance'
    | '/investments'
    | '/loans'
    | '/mobile-recharge'
    | '/open-fd'
    | '/payments'
    | '/pfm'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/transfer'
    | '/pay-bills/credit-card'
    | '/pay-bills/electricity'
    | '/pay-bills/gas'
    | '/pay-bills/mobile'
    | '/pay-bills/water'
    | '/pay-bills'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/accounts'
    | '/_app/apply-loan'
    | '/_app/asba-ipo'
    | '/_app/beneficiaries'
    | '/_app/cards'
    | '/_app/dashboard'
    | '/_app/deposits'
    | '/_app/govt-schemes'
    | '/_app/insurance'
    | '/_app/investments'
    | '/_app/loans'
    | '/_app/mobile-recharge'
    | '/_app/open-fd'
    | '/_app/payments'
    | '/_app/pfm'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/transactions'
    | '/_app/transfer'
    | '/_app/pay-bills/credit-card'
    | '/_app/pay-bills/electricity'
    | '/_app/pay-bills/gas'
    | '/_app/pay-bills/mobile'
    | '/_app/pay-bills/water'
    | '/_app/pay-bills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pfm': {
      id: '/_app/pfm'
      path: '/pfm'
      fullPath: '/pfm'
      preLoaderRoute: typeof AppPfmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/open-fd': {
      id: '/_app/open-fd'
      path: '/open-fd'
      fullPath: '/open-fd'
      preLoaderRoute: typeof AppOpenFdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile-recharge': {
      id: '/_app/mobile-recharge'
      path: '/mobile-recharge'
      fullPath: '/mobile-recharge'
      preLoaderRoute: typeof AppMobileRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insurance': {
      id: '/_app/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AppInsuranceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/govt-schemes': {
      id: '/_app/govt-schemes'
      path: '/govt-schemes'
      fullPath: '/govt-schemes'
      preLoaderRoute: typeof AppGovtSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposits': {
      id: '/_app/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AppDepositsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beneficiaries': {
      id: '/_app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asba-ipo': {
      id: '/_app/asba-ipo'
      path: '/asba-ipo'
      fullPath: '/asba-ipo'
      preLoaderRoute: typeof AppAsbaIpoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply-loan': {
      id: '/_app/apply-loan'
      path: '/apply-loan'
      fullPath: '/apply-loan'
      preLoaderRoute: typeof AppApplyLoanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills/': {
      id: '/_app/pay-bills/'
      path: '/pay-bills'
      fullPath: '/pay-bills/'
      preLoaderRoute: typeof AppPayBillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills/water': {
      id: '/_app/pay-bills/water'
      path: '/pay-bills/water'
      fullPath: '/pay-bills/water'
      preLoaderRoute: typeof AppPayBillsWaterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills/mobile': {
      id: '/_app/pay-bills/mobile'
      path: '/pay-bills/mobile'
      fullPath: '/pay-bills/mobile'
      preLoaderRoute: typeof AppPayBillsMobileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills/gas': {
      id: '/_app/pay-bills/gas'
      path: '/pay-bills/gas'
      fullPath: '/pay-bills/gas'
      preLoaderRoute: typeof AppPayBillsGasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills/electricity': {
      id: '/_app/pay-bills/electricity'
      path: '/pay-bills/electricity'
      fullPath: '/pay-bills/electricity'
      preLoaderRoute: typeof AppPayBillsElectricityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills/credit-card': {
      id: '/_app/pay-bills/credit-card'
      path: '/pay-bills/credit-card'
      fullPath: '/pay-bills/credit-card'
      preLoaderRoute: typeof AppPayBillsCreditCardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppApplyLoanRoute: typeof AppApplyLoanRoute
  AppAsbaIpoRoute: typeof AppAsbaIpoRoute
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppCardsRoute: typeof AppCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositsRoute: typeof AppDepositsRoute
  AppGovtSchemesRoute: typeof AppGovtSchemesRoute
  AppInsuranceRoute: typeof AppInsuranceRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppLoansRoute: typeof AppLoansRoute
  AppMobileRechargeRoute: typeof AppMobileRechargeRoute
  AppOpenFdRoute: typeof AppOpenFdRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPfmRoute: typeof AppPfmRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppTransferRoute: typeof AppTransferRoute
  AppPayBillsCreditCardRoute: typeof AppPayBillsCreditCardRoute
  AppPayBillsElectricityRoute: typeof AppPayBillsElectricityRoute
  AppPayBillsGasRoute: typeof AppPayBillsGasRoute
  AppPayBillsMobileRoute: typeof AppPayBillsMobileRoute
  AppPayBillsWaterRoute: typeof AppPayBillsWaterRoute
  AppPayBillsIndexRoute: typeof AppPayBillsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppApplyLoanRoute: AppApplyLoanRoute,
  AppAsbaIpoRoute: AppAsbaIpoRoute,
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppCardsRoute: AppCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepositsRoute: AppDepositsRoute,
  AppGovtSchemesRoute: AppGovtSchemesRoute,
  AppInsuranceRoute: AppInsuranceRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppLoansRoute: AppLoansRoute,
  AppMobileRechargeRoute: AppMobileRechargeRoute,
  AppOpenFdRoute: AppOpenFdRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPfmRoute: AppPfmRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppTransferRoute: AppTransferRoute,
  AppPayBillsCreditCardRoute: AppPayBillsCreditCardRoute,
  AppPayBillsElectricityRoute: AppPayBillsElectricityRoute,
  AppPayBillsGasRoute: AppPayBillsGasRoute,
  AppPayBillsMobileRoute: AppPayBillsMobileRoute,
  AppPayBillsWaterRoute: AppPayBillsWaterRoute,
  AppPayBillsIndexRoute: AppPayBillsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
